import "@/s.css";
import Footer from "./Footer";
import Header from "./Header";
export const metadata = {
  title: "shop",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
